### PR TITLE
Use the correct EOL character depending on OS.

### LINKED ISSUE #2: Can't send commands to stdin on Windows
First and foremost, thank you for putting this together. I have been messing around with Exiftool in a Node application recently and trying to get my head wrapped around how to properly send and receive calls to/from Exiftool with the -stay_open flag enabled. Your library makes this really easy to manage.

During my testing of this lib, I noticed that I was able to send and receive data through stdin/stdout on my Mac without any issues but couldn't get it working on Windows. The problem appears to be related to the hardcoded `\n` characters when sending commands to `stdin`. Unix and Windows have different values for end of line characters (`\n` and `\r\n` respectively).

This problem can easily be fixed by replacing all instances of a hardcoded `\n` character with `require('os').EOL`.

### PR DESCRIPTION
**Pull request by JAndritsch**
Fixes #2.

### CODE REVIEW

**Comment by z-vr** [comment]
@JAndritsch thanks for the PR, have you tested on your Windows machine? I'll merge today then.

**Comment by JAndritsch** [comment]
Yep, I've tested this on a Windows machine.

**Comment by JAndritsch** [comment]
Also, FWIW, the vendored copy of Exiftool you have isn't compatible with Windows. You may want to consider adding the EXE for Windows users too. I ended up getting your lib to work by just installing Exiftool on the machine and sourcing it in the constructor.

**Comment by JAndritsch** [comment]
One more update: I discovered that `process.kill()` wasn't actually stopping exiftool on WIndows even after my program had quit. I believe this is due to the `-stay_open` flag and how it works.

I was able to fix this by adding the following code to the `close()` method:

``` javascript
this._process.stdin.write(`-stay_open${EOL}`);
this._process.stdin.write(`false${EOL}`);
this._process.kill();
```

You have to tell exiftool when it should no longer stay open, otherwise it will continue to run on Windows.

**Pull request merged**
